### PR TITLE
Added vagrant and gulp task for minification

### PR DESCRIPTION
**Pull request by alxdnlnko**
Hi. I've added a Vagrant config and Gulp task to build minified releases (~9KB).

To use vagrant you must install the latest versions of ruby, virtualbox and vagrant. Then call `vagrant up` in the project folder (it will create a virtual machine and install needed packages in it).
After that call `vagrant ssh` to login in it, and `cd /vagrant` (mounted project folder in the virtual machine.

Finally, run `npm install` (it will install needed packages for building you project) and `gulp build` to create minified version of autoComplt.

Alternatively, if you don't want to use a vagrant, `nodejs` and `gulp` must be installed globally in your system, and you can run `npm install` and `gulp build` on the spot.

Don't forget to build new minified versions for every release.

### CODE REVIEW

**Comment by Fischer-L** [comment]
First, sorry for my late reply and thank you for the nice work.

I found that Gmail puts the emails from Github into the junk email box. The result is that I miss lots of Github notifications and respond kind of late ... 

Since this plug-in depends on no extra lib and different developers may use different tools/frameworks, I will leave this part to individual user. Let them integrate this plug-in into their codes by their case.

**Comment by alxdnlnko** [comment]
What? Are you serious? :) It's not about integration, it is the minification of the library.  You must provide the minified dist version.

**Comment by Fischer-L** [comment]
Yes, this is what I mean.
Like you use Gulp and I use Grunt and others may use their preferred method. Some people may just copy the plug-in and paste into their codes and run their build tool afterward.

But you are right about providing min version. It would be convenient that people can quickly get the min version. Just add the min version.

**Comment by alxdnlnko** [comment]
And again... What? Are you serious? O_o

> Like you use Gulp and I use Grunt and others may use their preferred method
Again... It's not about integration, YOU MUST provide a min version, and I've added a gulp task for YOU to rebuild the min version.

> Just add the min version
And when you'll make any changes, how would you update the min version? Do you understand me? :)

**Pull request closed without merging**
